### PR TITLE
Add bindings

### PR DESCRIPTION
**Pull request by ok300**
Adds RN bindings and flutter bridge files for the changes in `store-lnurl-pay-domain` branch.

### CODE REVIEW

**Comment by andrei-21** [comment]
@ok300 thanks for the PR, but **Check react native** job complains: https://github.com/andrei-21/breez-sdk/actions/runs/7643488463/job/20829923202?pr=1.

**Comment by ok300** [comment]
I forgot to commit one file. It should work now, can you trigger the CI?

**Comment by andrei-21** [comment]
Hm, still fails with the same problem.

**Comment by ok300** [comment]
That's weird, the CI worked on the exact same branch, but on my repo: https://github.com/ok300/breez-sdk/pull/1

Can you just trigger it again? Maybe some caching issue?

**Comment by andrei-21** [comment]
Hm, let me merge and see if it works on my PR.

**Pull request merged**
